# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ablyd < Formula
  desc "AblyD wraps around any program and makes its stdin and stdout available via a Pub/Sub system, Ably."
  homepage ""
  version "0.2.0"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/ably-labs/ablyd/releases/v0.2.0/AblyD_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "24a231602b28b1f4711fefb517bf45758cee3091b50fcaeb1fc710a85c1fd42a"
    end
    if Hardware::CPU.arm?
      url "http://github.com/ably-labs/ablyd/releases/v0.2.0/AblyD_0.2.0_Darwin_arm64.tar.gz"
      sha256 "cc5fc603e676e40eb3317940fcad77008989d9c6ac02197f590e05debe78fa99"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/ably-labs/ablyd/releases/v0.2.0/AblyD_0.2.0_Linux_x86_64.tar.gz"
      sha256 "b0830746092ca078b5bcf3fb3b374420e5353b53d42095503c8ce62f8800e6e7"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/ably-labs/ablyd/releases/v0.2.0/AblyD_0.2.0_Linux_arm64.tar.gz"
      sha256 "04c3f0e32878039fefb0997aa2a12a6d931b0e2591a17f1f8e92cd2093885b3a"
    end
  end

  def install
    bin.install "AblyD"
  end
end
